<?php

use AST\FileSystem;

ignore_user_abort( true );

if ( ! headers_sent() ) {
	header( 'Expires: Wed, 11 Jan 1984 05:00:00 GMT' );
	header( 'Cache-Control: no-cache, must-revalidate, max-age=0' );
}

/** Don't run cron until the request finishes, if possible. */
if ( PHP_VERSION_ID >= 70016 && function_exists( 'fastcgi_finish_request' ) ) {
	fastcgi_finish_request();
} elseif ( function_exists( 'litespeed_finish_request' ) ) {
	litespeed_finish_request();
}

/*=====================================================
 SCRIPT CONFIGURATION FILE                        
*=====================================================*/
define("AST_CRON_JOB", true);
if( ! defined( "ASTROOTPATH" ) ){
    require_once realpath(__DIR__) . '/load.php';
}

/** CRON LOG FUNCTIONS */
function write_cron_log($output){
	$log_file = TEMP_PATH . "log/cron.log";

    if( ! file_exists( $log_file ) ){
        FileSystem::create($log_file);
    }

    file_put_contents($log_file, $output, FILE_APPEND | LOCK_EX);
}

function write_cron_log_date($output){
    $date = date('Y-m-d H:i:s', time());
    $log_entry = "[$date] $output\n";
	write_cron_log($log_entry);
}


write_cron_log("\n==================== START CRON ====================\n");


/** REMOVE TEMPORARY FILES GENERATED BY TOOLS */
$now = time();
$tempFolder = glob(TEMP_PATH . "/tools/*");
foreach($tempFolder as $file){
	if( is_dir( $file ) ){
		if( $now - filectime($file) >= 86400 ){
			FileSystem::delete($file, true);
		}
	}
}
write_cron_log_date( "Temporary chunks file cleared successfully." );

/** REMOVE TEMPORARY CHUNKS FILES GENERATED BY TOOLS */
$tempFolder = glob(TEMP_PATH . "/chunks/*");
foreach($tempFolder as $file){
	if( is_file( $file ) ){
		if( $now - filemtime($file) >= 86400 ){
			FileSystem::delete($file);
		}
	}
}
write_cron_log_date( "Temporary chunks file cleared successfully." );

/** REMOVE DOWNLOAD DATA FROM DATABASE */
global $db;
$db->rawQuery("DELETE FROM download WHERE date < DATE_SUB(NOW(), INTERVAL 24 HOUR)");
write_cron_log_date( "Temporary data delated from Database." );


/** GENERATE SITEMAP */
if( (\AST\Helper\Sitemap::instance())->start() )
	write_cron_log_date( "Sitemap Generated Successfully." );
else
	write_cron_log_date( "Unable to generate sitemap." );


/** GENERATE OTHER ACTIONS */
do_action("ast/cron/job");

/** CRON JOB END */
write_cron_log("==================== END CRON ====================\n");